version: "3.9"
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3307:3307
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    volumes:
      - mysql-db:/var/lib/mysql

  golang:
    build: 
      context: .
      dockerfile: Dockerfile

    container_name: golang
    ports:
      - 8080:8080
    depends_on:
      - mysql

  # add phpmyadmin service 
volumes:
  mysql-db: